name: fomo
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip=25.0.1
  - pip:
      - wandb==0.19.11
      - torchvision==0.15.1
      - torch==2.0.0
      - tqdm==4.67.1
      - transformers==4.51.3
      - pandas==2.2.3
      - numpy==1.26.4
      - gdown==5.2.0
      - scipy==1.15.2
      - opencv-python==4.11.0.86
      - scikit-image==0.25.2
      - scikit-learn==1.6.1
      - ftfy==6.3.1
      - open_clip_torch==2.32.0
      - albumentations==2.0.6
      - diffusers==0.15.0
      - openai-clip==1.0.1
      - albumentations==2.0.7
      - tabulate==0.9.0
      - rich==14.0.0
