name: fomo
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip=25.0.1
  - pip:
      - wandb==0.19.9
      - torchvision==0.21.0
      - torch==2.6.0
      - tqdm==4.67.1
      - transformers==4.51.3
      - pandas==2.2.3
      - numpy==2.2.4
      - gdown
