#!/bin/bash

#SBATCH --partition=gpu_a100
#SBATCH --gres=gpu:1
#SBATCH --cpus-per-task=9
#SBATCH --gpus=1
#SBATCH --job-name=train
#SBATCH --ntasks=1
#SBATCH --time=02:00:00
#SBATCH --mem=32000M
#SBATCH --output=eval_output_%A.out

module purge
module load 2024
module load 2023
module load Anaconda3/2023.07-2

# change this based on your directory structure
cd $HOME/udit/FoMo/
source activate fomo

# validation variables
CKPT_FOLDER="pretrained_weights/fc_weights.pth"
ARCHITECTURE="CLIP:ViT-L/14"
RESULT_FOLDER="clip_vitl14"
DATASET_DIR="$TMPDIR/datasets"
CNN_DETECTION_DATA_TYPES=(biggan cyclegan gaugan progan seeingdark stylegan whichfaceisreal crn deepfake imle san stargan stylegan2)
# debug
#CNN_DETECTION_DATA_TYPES=(progan)

for CNN_DETECTION_DATA_TYPE in "${CNN_DETECTION_DATA_TYPES[@]}"; do
  srun python validate.py --arch="$ARCHITECTURE" \
    --ckpt "$CKPT_FOLDER" \
    --result_folder "$RESULT_FOLDER" \
    --real_path "$DATASET_DIR/test/$CNN_DETECTION_DATA_TYPE/0_real" \
    --fake_path "$DATASET_DIR/test/$CNN_DETECTION_DATA_TYPE/1_fake"
done