#!/bin/bash

#SBATCH --partition=gpu_a100
#SBATCH --gres=gpu:1
#SBATCH --cpus-per-task=9
#SBATCH --gpus=1
#SBATCH --job-name=validate
#SBATCH --ntasks=1
#SBATCH --time=02:00:00
#SBATCH --mem=32000M
#SBATCH --output=./tmp/validate_output_%A.out

module purge
module load 2024
module load 2023
module load Anaconda3/2023.07-2

# change this based on your directory structure
cd $HOME/udit/FoMo/
source activate fomo

# login wanb
wandb login

# validation variables
CKPT_FOLDER="pretrained_weights/fc_weights.pth"
# ARCHITECTURE="CLIP:ViT-L/14"
ARCHITECTURE="OpenCLIP:ViT-H/14:laion2b_s32b_b79k"
RESULT_FOLDER="results/open_clip_vith14_laion2b_s32b_b79k"
# DATASET_DIR="$TMPDIR/datasets" # not working, the env. var. changes on sbatch (todo: fix it)
DATASET_DIR="/scratch-shared/scur0555/datasets" # working
CNN_DETECTION_DATA_TYPES=(biggan cyclegan gaugan progan seeingdark stylegan whichfaceisreal crn deepfake imle san stargan stylegan2)
# debug
# CNN_DETECTION_DATA_TYPES=(biggan)

for CNN_DETECTION_DATA_TYPE in "${CNN_DETECTION_DATA_TYPES[@]}"; do
  srun python validate.py --run_name "validation" \
    --arch "$ARCHITECTURE" \
    --ckpt "$CKPT_FOLDER" \
    --result_folder "$RESULT_FOLDER" \
    --data_mode "wang2020" \
    --real_path "$DATASET_DIR/cnn_detection/test/$CNN_DETECTION_DATA_TYPE" \
    --fake_path "$DATASET_DIR/cnn_detection/test/$CNN_DETECTION_DATA_TYPE"
done