#!/bin/bash

#SBATCH --partition=gpu_a100
#SBATCH --gres=gpu:1
#SBATCH --cpus-per-task=18
#SBATCH --gpus=1
#SBATCH --job-name=train
#SBATCH --ntasks=1
#SBATCH --time=12:00:00
#SBATCH --mem=32000M
#SBATCH --output=train_clipping_output_%A.out

module purge
module load 2024
module load 2023
module load Anaconda3/2023.07-2
source activate fomo_gpu



# global parameters
MODULE=clipping
CKPT_FOLDER="<mode.pth>" # path to the checkpoint file
RUN=test # wandb
PROJECT=CTD-Test # wandb
USER="udit"
# change this based on your directory structure
DIR=$HOME/$USER/FoMo/
cd $DIR

# real and fake
DATASETS=(heygen MidJourney whichfaceisreal stargan starganv2 styleclip CollabDiff)
# debug
DATASETS=(heygen)

srun python "src/main.py" \
    --module "${MODULE}" \
    --mode "test" \
    --run_name "${RUN}" \
    --project "${PROJECT}" \
    --log_dir $HOME/${USER}/logdir/${MODULE}/${RUN} \
    --test_datasets "${DATASETS[@]}" \
    --checkpoint "${CKPT_FOLDER}" \
    --model "CLIP:ViT-L/14" \
    --clip_type "${MODULE}" \
    --batch_size 32 \
    --logging \
    --device "cuda"
