#!/bin/bash

#SBATCH --partition=gpu_a100
#SBATCH --gres=gpu:1
#SBATCH --cpus-per-task=18
#SBATCH --gpus=1
#SBATCH --job-name=train
#SBATCH --ntasks=1
#SBATCH --time=6:00:00
#SBATCH --mem=32000M
#SBATCH --output=train_clipping_output_%A.out

module purge
module load 2024
module load Anaconda3/2024.06-1

source activate fomo_gpu

# global parameters
MODULE=clipping
RUN=train   # wandb
PROJECT=CTD # wandb
USER="john"

# change this based on your directory structure
cd $HOME/$USER/FoMo/

srun python "main.py" \
  --log-level "info" \
  --debug \
  --mode "test" \
  --module "${MODULE}" \
  --project "${PROJECT}" \
  --run-name "${RUN}" \
  --model "CLIP:ViT-L/14" \
  --clip-type "${MODULE}" \
  --eval-every 500 \
  --log-every 250 \
  --batch-size 128 \
  --epochs 2 \
  --device "cuda" \
  --test-checkpoint "./checkpoints/clipping/best.pth"
