#!/bin/bash

#SBATCH --partition=gpu_a100
#SBATCH --gres=gpu:1
#SBATCH --cpus-per-task=18
#SBATCH --gpus=1
#SBATCH --job-name=test
#SBATCH --ntasks=1
#SBATCH --time=12:00:00
#SBATCH --mem=32000M
#SBATCH --output=./snellius_outputs/testing/test_output_%A.out

module purge
module load 2024
module load 2023
module load Anaconda3/2023.07-2
source activate fomo_gpu


# global parameters
MODULE=fusion
CKPT_FOLDER="/home/scur0555/udit/logdir/fusion/train/1748129590" # path to the checkpoint file
RUN=fusion # wandb
PROJECT=DF40-Test # wandb
USER="udit"
# change this based on your directory structure
DIR=$HOME/$USER/FoMo/
cd $DIR

# real and fake
DATASETS=(heygen MidJourney whichisreal stargan starganv2 styleclip CollabDiff)
# debug
# DATASETS=(CollabDiff)

srun python "src/main.py" \
    --module "${MODULE}" \
    --mode "test" \
    --run_name "${RUN}" \
    --project "${PROJECT}" \
    --log_dir $HOME/${USER}/logdir/${MODULE}/test \
    --test_datasets "${DATASETS[@]}" \
    --checkpoint "${CKPT_FOLDER}" \
    --model "CLIP:ViT-L/14" \
    --clip_type "${MODULE}" \
    --batch_size 128 \
    --logging \
    --device "cuda"
