#!/bin/bash

#SBATCH --partition=gpu_a100
#SBATCH --gres=gpu:1
#SBATCH --cpus-per-task=9
#SBATCH --gpus=1
#SBATCH --job-name=validate
#SBATCH --ntasks=1
#SBATCH --time=02:00:00
#SBATCH --mem=32000M
#SBATCH --output=./tmp/validate_output_%A.out

module purge
module load 2024
module load 2023
module load Anaconda3/2023.07-2

# change this based on your directory structure
cd $HOME/udit/FoMo/
source activate fomo

# login wanb
wandb login

# validation variables
CKPT_FOLDER="pretrained_weights/fc_weights.pth"

ARCHITECTURE="CLIP:ViT-L/14"
# ARCHITECTURE="OpenCLIP:ViT-H/14:laion2b_s32b_b79k"

# RESULT_FOLDER="results/open_clip_vith14_laion2b_s32b_b79k"
RESULT_FOLDER="results/clip_vitl14"

# DATASET_DIR="$TMPDIR/datasets" # not working, the env. var. changes on sbatch (todo: fix it)
DATASET_DIR="/scratch-shared/scur0555/datasets" # working
# DATASET_NAME="cnn_detection"
DATASET_NAME="df40"

# cnn detection
DATA_TYPES=(biggan cyclegan gaugan progan seeingdark stylegan whichfaceisreal crn deepfake imle san stargan stylegan2)
# DF40
# cdf and ff
DATA_TYPES=(fsgan faceswap simswap inswap blendface uniface mobileswap e4s facedancer fomm facevid2vid wav2lip MRAA one_shot_free pirender tpsm lia danet sadtalker mcnet VQGAN StyleGAN2 StyleGAN3 StyleGANXL sd2.1 ddim PixArt DiT SiT)
# real and fake
DATA_TYPES=(heygen MidJourney whichfaceisreal stargan starganv2 styleclip e4e CollabDiff)
# DATA_TYPES=(whichisreal stargan)

# debug
# DATA_TYPES=(biggan)

for DATA_TYPE in "${DATA_TYPES[@]}"; do
  srun python validate.py \
    --project "UniversalFakeDetect" \
    --run_name "validation" \
    --dataset "$DATASET_NAME" \
    --arch "$ARCHITECTURE" \
    --ckpt "$CKPT_FOLDER" \
    --result_folder "$RESULT_FOLDER" \
    --data_mode "wang2020" \
    --df40_name $DATA_TYPE \
    --real_path "$DATASET_DIR/$DATASET_NAME/test/$DATA_TYPE" \
    --fake_path "$DATASET_DIR/$DATASET_NAME/test/$DATA_TYPE"
done